# .github/workflows/test.yaml
name: Test Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "temurin" # Adoptium/Temurin est recommandé pour Java 21

      - name: Build microservice1 (progweb)
        run: |
          cd progweb
          mvn clean package

      - name: Build microservice2 (service2)
        run: |
          cd service2
          mvn clean package
